-- add good roles
INSERT INTO Roles VALUES ("PASSENGER", "PASSENGERS");
INSERT INTO Roles VALUES ("CAPTAIN", "PASSENGERS");
INSERT INTO Roles VALUES ("MEDIC", "PASSENGERS");
INSERT INTO Roles VALUES ("PRESIDENT", "PASSENGERS");
INSERT INTO Roles VALUES ("TURNCOAT", "PASSENGERS");

-- add bad roles
INSERT INTO Roles VALUES ("SABOTEUR", "STOWAWAYS");
INSERT INTO Roles VALUES ("EXECUTIONER", "STOWAWAYS");
INSERT INTO Roles VALUES ("ACCOMPLICE", "STOWAWAYS");

-- add other roles
INSERT INTO Roles VALUES ("RIVAL", "RIVALS");