-- add good roles
INSERT INTO Roles VALUES ('PASSENGER', 'PASSENGERS', 'HAS NO SPECIAL ABILITY. WINS BY ELIMINATING THE SABOTEUR.');
INSERT INTO Roles VALUES ('CAPTAIN', 'PASSENGERS', 'MAY VOTE TWICE EACH TRIBUNAL. WINS BY ELIMINATING THE SABOTEUR.');
INSERT INTO Roles VALUES ('MEDIC', 'PASSENGERS', 'MAY SAVE A PLAYER EACH TRIBUNAL WITH THE SATCHEL OF SAFETY. WINS BY ELIMINATING THE SABOTEUR.');
INSERT INTO Roles VALUES ('PRESIDENT', 'PASSENGERS', 'KNOWN BY THE TURNCOAT. MAY VETO A TRIBUNAL ONCE PER GAME. WINS BY ELIMINATING THE SABOTEUR.');
INSERT INTO Roles VALUES ('TURNCOAT', 'PASSENGERS', 'HAS NO SPECIAL ABILITY. KNOWS THE PRESIDENT. BECOMES A STOWAWAY IF THE PRESIDENT IS ELIMINATED.');
INSERT INTO Roles VALUES ('PROFESSOR', 'PASSENGERS', 'KNOWS WHETHER THEIR VOTE WAS THE SAME AS THE SABOTEUR''S. WINS BY ELIMINATING THE SABOTEUR.');
INSERT INTO Roles VALUES ('DETECTIVE', 'PASSENGERS', 'MAY INVESTIGATE ONE CARD FROM THE GRAVEYARD DURING THE MAROONING. WINS BY ELIMINATING THE SABOTEUR.');

-- add bad roles
INSERT INTO Roles VALUES ('SABOTEUR', 'STOWAWAYS', 'WANTS TO ELIMINATE PASSENGERS WHILE KEEPING THEIR IDENTITY HIDDEN. BREAKS ALL VOTING TIES AND WINS BY GAINING THE MAJORITY WITH THE STOWAWAYS.');
INSERT INTO Roles VALUES ('EXECUTIONER', 'STOWAWAYS', 'KNOWS THE SABOTEUR. MAY EXECUTE A PLAYER ONCE PER GAME. WINS IF THE SABOTEUR WINS.');
INSERT INTO Roles VALUES ('ACCOMPLICE', 'STOWAWAYS', 'KNOWS THE SABOTEUR. WINS IF THE SABOTEUR WINS.');
INSERT INTO Roles VALUES ('GHOST', 'STOWAWAYS', 'KNOWS THE SABOTEUR. ASSUMES A ROLE FROM THE GRAVEYARD DURING THE MAROONING. WINS IF THE SABOTEUR WINS.');
INSERT INTO Roles VALUES ('SILENCER', 'STOWAWAYS', 'KNOWS THE SABOTEUR. MAY SILENCE ONE PLAYER''S VOTE EACH TRIBUNAL. WINS IF THE SABOTEUR WINS.');